---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opnsense-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opnsense-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opnsense-exporter
    spec:
      containers:
        - name: opnsense-exporter
          image: ghcr.io/athennamind/opnsense-exporter:0.0.11
          env:
            - name: OPNSENSE_EXPORTER_OPS_PROTOCOL
              value: "https"
            - name: OPNSENSE_EXPORTER_OPS_API
              value: "192.168.1.1:8443"
            - name: OPNSENSE_EXPORTER_OPS_INSECURE
              value: "true"
            - name: OPNSENSE_EXPORTER_INSTANCE_LABEL
              value: "router.lan"
            - name: OPNSENSE_EXPORTER_OPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opnsense-exporter-secret
                  key: api-key
            - name: OPNSENSE_EXPORTER_OPS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: opnsense-exporter-secret
                  key: api-secret
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: opnsense-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opnsense-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: opnsense-exporter
