apiVersion: v1
kind: Secret
metadata:
    name: opnsense-exporter-secret
    namespace: monitoring
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:hUt/tbLMj8VNDmejlG5Ow4S5cYjkTxsHL62zJi/XsYmImKNNkiVzEAVEpJxwcyNSmyVEvwCOgFvQtTeRyQ4aHazd+plLUTGT9m1ztHX+bqk=,iv:u2qkJStSSJQrsUZq+rOfm6uNPypbttvunU0buZHIj6Q=,tag:4ZzDz09VuM+m/zfJ4y62iQ==,type:str]
    api-secret: ENC[AES256_GCM,data:YYZruhKeYIJ90BgFXhsvu9YJS08YD6g4vYueRH/YNxg4sXKW3kkt8wJt5vQsFEMTKgGAWLxn4yPI0B+Jb9+VMkmt6W3drXK98NyV4CNMjt4=,iv:nst8Kp17pEIgVra05pw4qMYyJDxGJtQtFgeHpD0n6jU=,tag:3mnFdDNoREpenEjDgyWu8Q==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MnR1c0NNZ054OEovNElQ
            ZytFOU9uZjlrQzZMMGxtRThSdW9uWnEvUlEwClB5SXhJQm16cDB1MWduU3dUbzFV
            YTRhZ1RRdkxqWUNnSUMrVDZ2Y2NhNDQKLS0tIFdCUHJrODNQNXNvbFBoNUVsVUhj
            U3VaRjJEcitEK2NhcjdtRWRSUkJhQkUKODHUHbp+5rBLn95749aRdOOsn9cAVpGE
            fKmlwOT5/hjWNy9CfYn1VY9lwxPfzLj2Z1IPWDipOhC6zGWh4zCIhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K3JmVURIYjRqanpkOFhS
            UFR1U0F5cUh5QXdkR1U3elpOdERIQ1hKZ2hRCmdwQkQ5U1VjUmZjYXl5VXBtaStq
            cVBEMWtIK2ZUZXRGdHdNTm1XS1AzNTgKLS0tIGorZFZtMUhlUFhEZE03T3VrNHdW
            QTZJTzRZYmxIOGV4WnVCaWptdlpoSEUKvx/7sGu4fHm/UWjAL4DUeOMm1WonhqrR
            6hlwxIVLiud//fZFCSUCpmyZe5t1o9GRyF279H43uXi5m/rRzLCCcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSW9VbVErU0dnMFN3V2x5
            VUNmVGFFSldoay9uMXR4UFgyNDlHV2pkZGxBCjBhUHBiOFQxWTh6T2xjZGtBYTlM
            WGhUUXpuZW02VkNtT0sweWt6WkdrdHcKLS0tIEJOaHFIS3ZQS0ZSMjd6Qm4wTTFs
            VHZLby9CZDd0enBYcnFRcjBCVDQ1WUUKWwJHtbSP06uoVwLBCJKlVaNvybcIiwg0
            EZhEH0ZnEqSvKno05wxzGJAsUyGSctG6VyWmPSAITmXpQok3ZPkc+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVkxaWDhTalJZKzUxbmhH
            Sm1zZ1ZhSWQ5YnZ0SUJjd1NYVnRDSU15bEJNCkhHYnkzcHVibTAyZmE5dlRTRnFZ
            M041cVM3U0MwK2MrcjA4dmMwOVN2RkUKLS0tIG1sZWlCQWROUU91SS9adldEc1g1
            Y0ZSdW5sd1dpcGVobkx4bEJ0N2d4UjQKeEoudiFe5wKRts/JYVRH9piSrNt4uEVh
            McmGipFFSf3u/WVJXjvJFzxiahFwEzNQTwNv41uRxgQr+gYuQzRUDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:27:20Z"
    mac: ENC[AES256_GCM,data:6P3rHyoj767pvNV4VloYEHmFQKQFc6hKGW/AJ9yHh2Bju+97wqst9GSfpZ3ATh6rKeBZNVcy2aoAfDMknCCkUE1al0zWB6ssNP3MkWce7GJW9kdVr2+p7pdaXmQHCZj0HiDTsAAl7ME9VOLlX+seh20Lq/ZOGz8tJNqfkkzLm6c=,iv:gGlT3iIZCUMKDbEy8sfDWQUvcsz40VzN1bnmvXFoD3s=,tag:JQtllZLab76m5u6aqE2Jlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
