---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bifrost-tls
  namespace: bifrost
spec:
  secretName: bifrost-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bifrost.dimensiondoor.xyz
