---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - helmrelease.yaml
  - ollama-endpoints.yaml
  - certificate.yaml
  - ingressroute.yaml
