apiVersion: ENC[AES256_GCM,data:dL8=,iv:S/M/VxN31G1HtswpbrVXACxoYk7Y5OEpN+YFWegxUDI=,tag:rFYaYlo/tADZuP9+y7trTg==,type:str]
kind: ENC[AES256_GCM,data:hyIfPQ6i,iv:lq1c2jQxELtBuG5IT6KuW3RIoPHKuDWSEcmhgAZLkHM=,tag:yORXq2bgNfFJNRJlfq2vgA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5plRAF/rqMHhtJDE9quR,iv:2p2K5IZiIxKL88zQQVm7r3pLKn/X1iIefC8i/vtdQAU=,tag:e+u5t+nyKTjbzt5GAFn/Nw==,type:str]
    namespace: ENC[AES256_GCM,data:xQervuEtzg==,iv:Cy4f8fcOS+TWCgXolLN2LOIh9uOOfZS8ktbBTILmxxo=,tag:PC/Oa8ArvZELB+xS9+3sVA==,type:str]
stringData:
    encryption-key: ENC[AES256_GCM,data:3xo5fVnAVkdyv0n5RtWaIhkobOcJ50ZiZV+fusQYRTOn/ITQkHiDq6C6oBQT+rEfBpWL6gv4RCwFP0e6kNciyA==,iv:AJ2aBOU4Bo9siA351WFlsefSRyxEgo+66URzfSYILYU=,tag:XqEjOGku11821geBi2YH5w==,type:str]
    deepseek-api-key: ENC[AES256_GCM,data:QOikazX8WfMIbqMvX3PCmlD3iW/V28O6HwEHrajMGGTdxN0=,iv:BfN/9nn+q/3TgatUUtDD+KXkePRuYuw2JHCHuWVGOL4=,tag:oHB0WUnKmrISck1CHfTL7g==,type:str]
    zai-api-key: ENC[AES256_GCM,data:ayCl5THKNu40r4bBVQ1obUTVN7URD3tg2t3uJ+99TAOm51HlnUnc/jgLo/LAeEbk/Q==,iv:F1Ori8e/M917AFokAK+rJcwI9ixca7r8hxhKREcwg+o=,tag:N4rXLtWhXldea9OVVwnuwQ==,type:str]
    cliproxy-api-key: ENC[AES256_GCM,data:YicbGGsVgfQD0bEf2iixEa24jjhV3elzjRnofKibmsfQ/vSjNlEVf6u6pADV6S+lOMJLi5FuvmY9p7jyx4vojw==,iv:aDkuiwIIqZaEUFa6bl4ekHXs7IEsPXPAEoV8gHITOEw=,tag:w0RSCL9aUTAPmZSVH7f0IQ==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNUNmN1F6YmtpcVZ6bUFU
            alBOODlsYmtXbXRGaXBzQ0pXMG1JU1VUaVZBClV0QzNNdWNUc2NnaHBwTDU1SExh
            N3lXaStoVkFXMzFqZTRRQzRoS2ZUZkEKLS0tIFhpY2h4eU81WTZwYUVBSDVqaW4r
            MnF1Mm1yb2xRVDJabzVWaG9kT0lwTlEKcRLh8efjapVLggZTaTHoZSh8OFiX/UUt
            fvwsSvqmIdsdJ0BHIsmgRC9htIzwszFiZeZgBX4nwVrruLMze37o1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM1ZXQmhBSG1aaXF2Ylgv
            aFRzMU9Ob0N6cU9ZdkkyUlpaaTFRZE5xSEVNCkN4ZHhRZUVrYkMvbEw5SUJHbXVC
            azdzUmI0NjNQMXl5d3JQSFdkeUFMNW8KLS0tIGhqdFg0VEs5bEN5OFdzRXA4ZjVw
            S0UwblNMcUpjU2FRMmVtYktpRmJ4dm8KAU8Hv9Uo1KXjhZZ2/bR2xclVn0HXeHzc
            7x0yOh99jHbCH7l+ghQ7oYWJpe4jKREL+haov0hrn33ibS8+hfvMlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTG1IQm1MeC9FU2JtaUd5
            c2V0T2xtL05nU05YK0E3a213ejlpaG1DM0JJClN0clhUd3NtYUJWRmF6dVZPT0sw
            d3VDMVJ1NWpvTWhlNWZVajJ1c3Y0UUkKLS0tIFNXMFYxMnltWWx3TnVRZ2hGMWxZ
            ekl0Y0Q1YTF0M1dLMW15eWkvR09pRU0Konx5HGJeudn7lfTMlvwj7KEuMdPMU9Yk
            vPmZkVhpo6fSCdqWS3+QJ3nXlZNHtZNdHo0S5vetn6kt0lEo9p693Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQkhOcWF0UTJCMzM4dUQx
            MnZ4UWV3eDUvSkRnZTFWVThPMW1tVG1rYURZCnhzbFJQYTh6ZnhaY2cyekl5MGZi
            MFY3dk9CK2dkb2haMzljT20xOFZwNmMKLS0tIEd6dENid29sSjN1cDA3Sjdtenl6
            RGJLbnZxaHpBZTVaeGRGanFhUThaKzQKEtf1i7NEaznwfy97uqMRIDZFxmaG10h2
            bEOl9gdDfR772dHNItMmINBll4ghVz+wud7YvzTPdPJcmyhlvyAJmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:32:03Z"
    mac: ENC[AES256_GCM,data:pNQZZcq+ExQUYxO0iuRplHNaN+mXEoxlXhnvkaOK/UXsNnfMymP/JzlmDOUltg8vP4Ug0qZADDOD32BnHAtDYBRoPX0aSCV+/Kw5p2qiXD7avYXC93+kJHUfIB7EbmnW0bw2glA71tO6CYPOwF4wzAjCZtyvaqt1x90CKgI+kLc=,iv:9uiCZ7UgcLGgXrMyanogSOfv1U/g4FM1TBNCGYlOfSE=,tag:tTP7depH+4IiBhcZbHK5lA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
