apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner
    namespace: forgejo-runner
type: Opaque
stringData:
    runner: ENC[AES256_GCM,data:Ir+2v3KUD1i/nJVGgYyL+Zpc5nJqaMczJy1WrVqRHtXhjmA26jra92qvjmnQ0gozKk36+7tHXoB6lkLHR+v+jl5WBPUVp5xxI09ABB8I4kWl0v1mjHbC60eEpKeJ9xa9NlOLmQ1wNwW+M4aeqg7+rFIQ3o6rn/P62FhwdArgJfVX1u+WFBOCJ0kwxAnxqiIfHdZ/w09ymxzqQaapphiyQCAKH+Z6GClm+79UdAHX8LQkiwkZ2QxShx7qFL1o0CMSXrjB8hMP2yYLG8SZKqhdRKyUTUW70bi2Fr0EI+BDqk4JKYrTG+ugF3Mg0O/hHC76Vtu9yiJHOHlvH13+9LmRNu36NwOdONib1EEMRZKdT0VQQu5D2MKUKrBF/brfJZq5gXUYRyO1Tyao6w2LcdONggc0HrLJh13vvidgOwBdz4ISSb7wc6m0mFBfJV7594ZAnLDIe7rOBk3uwZQfcTeX6KPMUhA4/3m6/umuiXfs093dyWteUZEZZ8BqfJWzvnjKjLkm9teC3qZR3hoM2FzgX22xQ3Te7RgNvo0lc1UnsrcQ3+87Dizws+3zuy5V6kvW1S4AE0PzAmhla6PocMxFWmFsf+0=,iv:iVn4Cw6zZtsRuLZSPborfX5X0OlsW8wTykB+qOS4JGw=,tag:eGzKpdtDjzRrklR0tUaZ+Q==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSU9HOEU4R05FUDgwMHo1
            a2xPOEIxSjBuaUUwTHJQb3Exbm9BTmd3SGxnCjdRSFI4NGxLQ0VWU2RjQWdHMjd0
            enpYV1pMazNrY0UxcGVhNUJvVjZ2VEkKLS0tIGpxNDJzcFN5RUFoWlVsRStwRWM3
            NDBMWjY1NXMwY0ZJcjNoVnY0T3BTSlEK/15jUGt5fbWAJKpdMGdn/ex67CUA1T1j
            n2lOg0g4riYXyIGp+DE+3dDuRd47NyOpYjx1bJHGLX44FcaUVx2geg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTkZMUEFmK3ZsbC9zWXFS
            UTVMNlZGMkhkZXFsUXdZVmhjajdEWGMrVG40CnZjY2hRcmdFc2V0Y0dydThmN3NB
            emJONFZmU0o0RnBvVHIwL2JYdFAwYjgKLS0tIHZVVENVbGsyOWJDdHJkTWd1aFdx
            RytCRzdYak42YWlYK0NzSEwwckhhYTAKfukZUpHwZx9OUpU5Nsu0V6FdpuPJokxQ
            db9Cd4zsluoxk9IpQgWRr+DvwZg5yJkjmhHgpgIKLQPQZ3pjFt8GWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVHV5YzcyZkRkd1JyVFRQ
            bFRpUDdjdXNsYzVEeU1rMUJoSmRsME53OWxFCnJyeCttZENURVF1Z3l0bnhEdzVS
            ZzcrcVM5T0lwTVQzVmlSaUJ0WUtPZWsKLS0tIHkrWFI0bGcrd3JpZUtNN2ZhaFRV
            MEdDTEZwS3k4cHJuOUdCN0ZQd3pnWGsKMN/8NudSDfGJMrdlPAaruCOW9AQBF68X
            /FcHxLcGQ+jNzH4VsO24q0Qh6TtPdatPFFCVsxcyUtTfZuMDFQ7ICQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a3FuS3pNN1luUXFNNkQ1
            NGV6QmZzVFFORnAvUzFxUWdMaHVOTVFzdVRFCnpSOWtGTE84SnBoMkVLR0ZWdHZv
            aDhiSlNiY2twc20zZGhkaWF3WlU5ZmsKLS0tIGhmTEljdmdNaHBpbFlJY3hzbWgz
            bjQwWE5YeEdCMTJTcWl1bEVRbE1WV2MKNDlC2xxZwVL1TxB9tthaYoehtrpnUJWJ
            rW/e9ENtm336Dm71EqjMNNOvKLC39FHM8VFgEIsJLOQxrdi9Q3Teug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T00:18:41Z"
    mac: ENC[AES256_GCM,data:trIxEYg7OyQCtHjIzg5t3Cxp836wp5NiQ3482u/uj2dFFURz2YVt2fdz5FMXpU6LVeuBvIoxhIzCW9n4wgYaqKOCK9MyH0Qz1x1An9umciMqSEvsIu3NIgUvROhLxIqZseo6d7c3d7wLGv72QeG0S/VE7RMljzS0TGs2H2llJr0=,iv:LOUCcLv5ttg6bpKZ3JuzQyEOH4GP6QPwHCbn0niqxjk=,tag:tsjJmsgkYsHKOZbEYqUmjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
