apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner
    namespace: forgejo-runner
type: Opaque
stringData:
    runner: ENC[AES256_GCM,data:iHXseEdh2H0wqI8gZQ4MzVtJnIIKDdi4uk2aGbxePaBlBbsvrrmJKkOYATfHTGKf1dQGiO8uJ0sLg72pEqpiE6xccLrWPbUBfeUnnkw2X5zqAIJz2UtR44D/43mwi73j/oKK49V7Cm/LuHoYIO4k39u6htZUTlyuoB7nCzJ+hSkSwEVrcOrqhDgRtAS9EOdKAS4rlT5U6/PYtiR57VMdGRhPBypcMuTiyfNek74zmemRy5GNuTGRJWp6IVqDMUkdbtYVUutZpa7EXjR2xDh28C6hyDgCBlAU7aTqmDZ1U3F52/QHYlmjyAQqlH8k5Pbya1iatc6ojUuS47E4/DeSyH5WsadJdw6CxDqkcjiFdynbRvueVEdRucYxi1iircypXqj+mDc1NhynDk9Demu/LGLGr/ITpgQJBRSagAyYHyztBfp53o70d+rDkHsj+FrfjkKnw4B2YEC2BQ7kxTp6Az8/NIynRt8diW6NGEargiejawPinxDxa21AuR4cNWKy7sn2CdEF4v4g4YeDTHCwxgbll7bdqyLRLQSxDmLPlnnmZhTlGOk13ixc9MrriVPdmVp+rMjz+ziHFZxOx8ZicetqSs+5lYRn,iv:b1w6V6+scrE+eKpN65jyV7GTbbRdj4KN/L7ESEoiFXc=,tag:H17FxuE35N/nik3+W4WsbQ==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSU9HOEU4R05FUDgwMHo1
            a2xPOEIxSjBuaUUwTHJQb3Exbm9BTmd3SGxnCjdRSFI4NGxLQ0VWU2RjQWdHMjd0
            enpYV1pMazNrY0UxcGVhNUJvVjZ2VEkKLS0tIGpxNDJzcFN5RUFoWlVsRStwRWM3
            NDBMWjY1NXMwY0ZJcjNoVnY0T3BTSlEK/15jUGt5fbWAJKpdMGdn/ex67CUA1T1j
            n2lOg0g4riYXyIGp+DE+3dDuRd47NyOpYjx1bJHGLX44FcaUVx2geg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTkZMUEFmK3ZsbC9zWXFS
            UTVMNlZGMkhkZXFsUXdZVmhjajdEWGMrVG40CnZjY2hRcmdFc2V0Y0dydThmN3NB
            emJONFZmU0o0RnBvVHIwL2JYdFAwYjgKLS0tIHZVVENVbGsyOWJDdHJkTWd1aFdx
            RytCRzdYak42YWlYK0NzSEwwckhhYTAKfukZUpHwZx9OUpU5Nsu0V6FdpuPJokxQ
            db9Cd4zsluoxk9IpQgWRr+DvwZg5yJkjmhHgpgIKLQPQZ3pjFt8GWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVHV5YzcyZkRkd1JyVFRQ
            bFRpUDdjdXNsYzVEeU1rMUJoSmRsME53OWxFCnJyeCttZENURVF1Z3l0bnhEdzVS
            ZzcrcVM5T0lwTVQzVmlSaUJ0WUtPZWsKLS0tIHkrWFI0bGcrd3JpZUtNN2ZhaFRV
            MEdDTEZwS3k4cHJuOUdCN0ZQd3pnWGsKMN/8NudSDfGJMrdlPAaruCOW9AQBF68X
            /FcHxLcGQ+jNzH4VsO24q0Qh6TtPdatPFFCVsxcyUtTfZuMDFQ7ICQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a3FuS3pNN1luUXFNNkQ1
            NGV6QmZzVFFORnAvUzFxUWdMaHVOTVFzdVRFCnpSOWtGTE84SnBoMkVLR0ZWdHZv
            aDhiSlNiY2twc20zZGhkaWF3WlU5ZmsKLS0tIGhmTEljdmdNaHBpbFlJY3hzbWgz
            bjQwWE5YeEdCMTJTcWl1bEVRbE1WV2MKNDlC2xxZwVL1TxB9tthaYoehtrpnUJWJ
            rW/e9ENtm336Dm71EqjMNNOvKLC39FHM8VFgEIsJLOQxrdi9Q3Teug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T23:17:31Z"
    mac: ENC[AES256_GCM,data:5ReSQLgm4KQ2Pbsta6S7AdQdoFsRf/DxB+Alctfj18HC/yn7/isACwbFLC3bk6+J7Q3M253YKFtCEbWfGmDE6X3TbZc0KO3PKHH5gMyll6fU6k0vFWNma1XVQ6byrlfH0l+W9vDnDij594zHDXrPI9k4Zgxn2HyNEE31VkjK0sE=,iv:1acNoDfr30QzE2kB0vmeeKAXh1NwsuxayvH4IFdm7oA=,tag:+2U2odRmL93Yx/9iBcRfmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
