[cakewallet]
src.github = "cake-tech/cake_wallet"
fetch.url = "https://github.com/cake-tech/cake_wallet/releases/download/$ver/Cake_Wallet_$ver_Linux.tar.xz"

[moondeck-buddy]
src.github = "FrogTheFrog/moondeck-buddy"
src.prefix = "v"
fetch.url = "https://github.com/FrogTheFrog/moondeck-buddy/releases/download/v$ver/MoonDeckBuddy-$ver-x86_64.AppImage"
