# IMPORTANT: This file must be encrypted with SOPS before committing!
# Run: sops -e -i k8s/apps/voicemail-receiver/secret.yaml
#
# After getting Telnyx credentials, update and encrypt:
# 1. Edit this file with real values
# 2. Run: sops -e -i k8s/apps/voicemail-receiver/secret.yaml
# 3. Commit the encrypted version
apiVersion: v1
kind: Secret
metadata:
    name: voicemail-secrets
    namespace: voicemail-receiver
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2oXsJXDNRlt3vKytp/WRc1NwidS1b6DPJ9AfoB5uyGbJuoCphsY1XUxAtziZmmGxUQ==,iv:OGYsr3JMr7v0X1tdA6GtpTXKCpBw2l0vqdN5vE5wMiU=,tag:SorOt7wCbWYe4bIv+/rJ5Q==,type:comment]
    #ENC[AES256_GCM,data:+z1Zj4EG/pkcGhdbWGXMTm9CjvA1ula2S6NaTf8DWHVCqMnvksMoonax8qsHkX9YN8w=,iv:3Wm/CC7I9uW+m9aDEk0dW1c3sB7/RZCC5FjYO4M7dMA=,tag:WmsQIFS4VJJHgnSHrYA01g==,type:comment]
    WEBHOOK_BASE_URL: ENC[AES256_GCM,data:kUMke4ZlvnONRg4JGjeEUd7z6R3TdRamu/gpJUMapx17aK4=,iv:mCCBYX2RfRPuiMzJ8xkOadKrFX+1Nj48SpthWFTUhJs=,tag:mJ2UH0Gd1kohw3Aha84QKA==,type:str]
    #ENC[AES256_GCM,data:DsQlmNA+pjoDxOL6HkehUqAYzgiJMvnly431jd2YieeTD0gGoVyHG9n7GlnmdlQF3evd9q6AFkFkC4yESz5nJj7Nkxj2loMpq6t7/A==,iv:dlkCzyiooMyo0pTI3Pd0MZ0wdrlyrKadvmqSbfL7TbQ=,tag:d3qkPZ7SJTX74GCvJTjNEA==,type:comment]
    #ENC[AES256_GCM,data:dqsv2Bbtk9BwaJ1kiCwtw92OTmawl788yogGNRYVjNAqEZApNXp2GLrfrzfx,iv:ZXIKk/dhM+K3jswKQWVDQlSVZNelcNF+WkG96S1oQaw=,tag:GzWRFNlMCq+8SOSzccUixA==,type:comment]
    TELNYX_API_KEY: ENC[AES256_GCM,data:D2sTz3OcDMn+hJpRU+CeLFxMAtb3Urpnz9pP,iv:lw7DsZYGtr/Cz3rFevYybPUMtJ1IvR3b4Lujx867S5A=,tag:S8fi0CHArwUx4V5slzQYQA==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZC9yL2w1YUp2ZU1kQnlN
            RTdzZTBKOENpcjFaR1FVd3pzeVJOTjI5Q0Q0Cm9BUkN2MVVQTEZ2TUhMS2NuUUtJ
            dmd3VkQwWk5Ib0R5ZlR5dTllVHN5bDQKLS0tIGZuYVl6dSswV0I4c1JVQm9kemNj
            WDdxSEFlNkZtMnRiU29nVXNvc1BKcjAKlXIkMxjHizatKwoU8TSkmuT/DQ3nyRO9
            k87hNWdPxVpCuoJ9oRYYQdQR/miCNr7tRB+g1Xfb8AjMg6c2NgPwug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SUFzLzFZdUsrcTlCQ1Zp
            enVlR1JHbmtkMGh6TFU5aENlRGRjMzVFaVFBCkZnWlJ3WHlQZ2dwOEpHSnVvSTEz
            WXVvQ0VsUjVhcjhOTkpyT2lPcHBCbFkKLS0tIFBBdXVnU0gyZm5CcTA0VXIxOW5R
            S1ZaTUN4WXozR3lKa0xrQ0x2MWlJcEkKbKQ3woM4W3k0KhxgbK+QyCaxVNh9Zy5L
            Og6jX2sO8zjBhVRKR2THs/GrdriFbMHfeq6mNijqVQ04xMovQm3n/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV3dkK2s5L0g2eXVGdkVK
            SXhsUUZBYXhwZXhGU21ZL1BuVzBTUThIL2pJCkVFbXF4S0VwNjRya1pUQ0lJVEhz
            T3FYVmoyc0ZyVktOY0VPVlZaaEhuVVEKLS0tIFJ1Z3RiQXI1eXhLWGF0ZmZqYkl2
            YU5pUWZHU0V1M3NjeDNVcU9KTXNXcmMKAGfQUVqFvUYHR+OqAtzXII44JRvli4n+
            7WJ4LRDvH3PbP78H9x37InP4+IQM1KNwlJwJZC1pvKxJww52HKUcmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaW5zcmFjRE9NbHl4T3FH
            aXBJZ3QzWmhKZFRYS05Bd21TNzEwWWd4clhZClRST2c5UTRPTXJwN0FvRmgrbUxS
            MFJFbUhVc1JUTHIxcTdvZkd6NGJJc28KLS0tIFJzYzZDK1UxaFZzNXE5YzhNWk42
            U2xuVUp3YUREZjFOYXU1RmVMb3BOYjAKiHXT/fwzaCYhIDST4o8uBR7cYfJO9qES
            lxc34ALYY8q05T+CK248MUfo0ITdJxsVW8Ce1s4X2Q34WFG5kstbpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T18:30:45Z"
    mac: ENC[AES256_GCM,data:MKVDp18uwTUl/hn7rAlzMulJlnAJITvjiImkPKS5/5dcwfF+SWhdQw0vvh2uM2VyMR4e4scjaW5ZhxNaOWj5+Qqh0JEIjpW9gTXKRTHtsArLzSPg0Bfpcx0IuI1iRWdpIwvYm4lvhhO52dP9Q3wfG7ImdQdaBfYLRwY3IDJl0yc=,iv:UclF3Ws4tZJ+Z+RSZ4a4tssB9+988SKsSw0XXYlpVoI=,tag:H5Wgw12NyPpXAeu18w6C9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
