name: Deploy Postmortems

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.forgejo/workflows/mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            docs
            flake.nix
            flake.lock
            mkdocs.yaml

      - uses: https://github.com/cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org http://192.168.1.27:8080/middle-earth
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= middle-earth:QJM6g097RUDyZA0OG00fXc7JxFMOXN3J5ZBX8j+QfFI=

      - name: Build site with Nix
        run: nix build .#documentation

      - name: Push to Attic cache
        run: |
          nix run .#attic-client -- login local http://192.168.1.27:8080 ${{ secrets.ATTIC_TOKEN }}
          nix run .#attic-client -- push local:middle-earth result

      - name: Prepare site for deploy
        run: cp -rL result _site

      - uses: https://codeberg.org/git-pages/action@v1
        with:
          site: https://ananjiani.codeberg.page/infra
          source: _site
          token: ${{ secrets.GITEATOKEN }}
