name: Deploy Postmortems

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.forgejo/workflows/mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: https://github.com/DeterminateSystems/magic-nix-cache-action@main

      - name: Build site with Nix
        run: |
          nix build .#documentation
          cp -rL result _site

      - uses: https://codeberg.org/git-pages/action@v1
