---
apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: zot
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.56"
spec:
  type: LoadBalancer
  selector:
    app: zot
  ports:
    - port: 5000
      targetPort: 5000
      name: http
