---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Headscale"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "headscale.png"
    gethomepage.dev/description: "Tailscale Control Server"
    gethomepage.dev/href: "https://ts.dimensiondoor.xyz"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ts.dimensiondoor.xyz`)
      kind: Rule
      services:
        - name: headscale
          port: 8080
  tls:
    secretName: headscale-tls
