---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Authentik"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "authentik.png"
    gethomepage.dev/description: "Identity Provider"
    gethomepage.dev/href: "https://auth.lan"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=authentik"
    gethomepage.dev/siteMonitor: "http://authentik-server.authentik.svc:80/-/health/ready/"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`auth.lan`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
