---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
  - cronjob.yaml
  - runner-configmap.yaml
  - runner-secret.yaml
  - runner-deployment.yaml
