apiVersion: ENC[AES256_GCM,data:qho=,iv:s4VdXoYwYtiJrppOqO8Mmq5JJNBxmmXpRmbEI+V3igc=,tag:c0tJXycE7eJ4tCyP/HExeQ==,type:str]
kind: ENC[AES256_GCM,data:3qbY2Sqo,iv:PoKxOtqIrOCTKxW9YncNz9AfLwTDEneLMtA0GFGNm8Q=,tag:jnDbMxBS2UT5Y6P4t2Uxiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nFH5oYlBWDoNv8KrEfds,iv:E5xwfwtvNPQb5xh+cWgAHjjxLdIatuIeD6WYXPDR3Gw=,tag:V+iujJ3HLiKmoQZs5K5BDA==,type:str]
    namespace: ENC[AES256_GCM,data:QId1AFegOA==,iv:m03u2vqKLjzwMYV9zJ8BpeE3VuAxMoMK90l1rdFfOlE=,tag:KgcMt3nOF07qw0LVvjdmRQ==,type:str]
type: ENC[AES256_GCM,data:jan9z8gl,iv:Yqt28CSWnWT31h6hX9ZvrD4m8czjkIm+JtBX2fp5vF4=,tag:nCwCBnUFGrQ0ISDLJd9f4w==,type:str]
stringData:
    #ENC[AES256_GCM,data:cvxcZYNEn6d85PZDSTKDQG67iub3edg=,iv:QUm2ezkNDd99ucmwOO3MpNxteLjaHToijwZS29VWHJA=,tag:Eb37YcqkLd8XyA28tDPE7g==,type:comment]
    admin-password: ENC[AES256_GCM,data:xPPjrRafpTlHE44zwrcg83+fcEkLq+iVLbGfh4gdj/g=,iv:opINDP1bFnTpnfY4Rr8CvE9DsJH0Yxpb3QQX+tiHCZI=,tag:anG0U2wU2TlRobkZSeIw1A==,type:str]
    #ENC[AES256_GCM,data:l5qFaJev9OiybDJBK+juU/yuhLI=,iv:Qwiyc0juNLvb46MDtv3YT/0RDKY8c2IGKLAqfzTqTss=,tag:m9jKy8SUu3yqYW2rBFGziw==,type:comment]
    postgres-password: ENC[AES256_GCM,data:P7dx3Z5rvWLmIRJIMYNRJ01wg8zXmO1RuH57sPYs8mo=,iv:qfFBcMkB2HNtdasAf8bFGqwMwD188a4bu0bw4tB4aLs=,tag:4jRn6XDSjS97iLWxEA9h2Q==,type:str]
    #ENC[AES256_GCM,data:Z+5Q+p1cyKRKj5/MuwGfuzlLOmODpSFnOupcXlzt,iv:TE2iG6YhbajawoaHtkZ8yZfU8O86Dqbpyc/zp0H2TOA=,tag:w55mK4Hu9H1rE3/LCVPNgQ==,type:comment]
    #ENC[AES256_GCM,data:Oin88yX4iL6G/YpauZfgBO8j3ItBX4HxPGCjZdm8bqzPk/LSFC48hRsFt/ADuvQkhbgE7aylgF0EPgPPEoqrToJgBjBRTxyqeRC+fCt3MYE=,iv:P6BDCY5e3DJrhqZDTFJqeH+s+S22Fnrd+zVvAN5bGjI=,tag:GdTUFNyVxFuTLoi2Vm07+w==,type:comment]
    #ENC[AES256_GCM,data:KFhqnyLhwY0BsUpfOkq5KRSEPBW0IyRMv5VY7YySCbwklUr5s8k+,iv:fNpSZtjv5GQ52iic8xDcXGwRwTS5ImX5hwjKVVrxZMg=,tag:+iNHv2KHjPwcr/PZ9Jzq8g==,type:comment]
    oauth-client-secret: ENC[AES256_GCM,data:izLQFpNMTy73MZqEGCAuDsGB2VUHJiwA90AkKeLvoQq/0O/EWq9f9SXvlPI=,iv:zoAJnZikf54w6dVjuZ2FRg+gAstv1hAfWhHNqwsa7nI=,tag:2SNH7XHTs4Kj1bGG+3ybjA==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2x6cXlBNU5FM1VoYUV5
            Wkd4eWpkVXIxMk9yeGp5ZHFjTUFOaWZJOEZzClpPcGJ4OVMvRjhsU1AybmZ6YmZV
            bUVhUkxLTEt0My96eUo5NVFmcUU4SFkKLS0tIE5IVmZ3Yngxai84dSs0ZjVrTFo3
            Mmt5alZ5VWJzM294bHd6ZXczZTh5Z2MK5BrIulqYYTUzniiUEy9pfc+yBYeoXBDL
            uESVpUQckNVgWZcKLCJdKe/GzkGX/KzAr+pbT3pd3xgzJu2V/NOOQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWGk2RHZYZ0R1UDRPeUNT
            T2pvdXlPcE9SWCsxWGd2NmlRUFNsM0o2UEg0CkZXSFNwUFdCaDRqMnZSVjB3RXlv
            Wm5mTG5RQmwwblBvb1g0SFJrQ3o1YWsKLS0tIGFjVkk3bHczRUJpaVNHZjcrb3VB
            NkV4MytBYy9uYjAweHY1QnJUWEMzY2MKmN34A5hKndeCqiBhmcKdKSZplRq8Id7M
            ihr3jCj3HT/OKe0IKh8gIhV4sG99EDSWT10qZBwQiWwzM4NSCmgV5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZUtpK0pmSkllUTFyanFj
            WVJ2Tm9UaU1oMDc2NCtzcXhRVWFVaEg1UzJNCmxHTFFuZEMyNmFiVEJmU0M3OVhx
            aUQrL1hDWGlMZFgvemNHU0R0SjY0bEUKLS0tIDg4dDhPczFCcEx3UmlFUk9yWThh
            REFabytsQmNZdWUrN1hoZjYzams2OTAKXD3tZ/TmrAeC8GsqBTFDqKmnjhEdtHPF
            EmdKe7ArsuHlUYlB7h71aKNOmf07oVIVjVKIXGuJCQep9QowUPqUwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbGRBMm03bWttaCtaOGFO
            enk4blhYQ2lSUDRmZ2VqMitIQXVVdWJTNlhBCjJSWVJWYTBsVFFrakJXeEhReUpJ
            VjZwT201eU14ZjA5dm5od3dseGV5S1UKLS0tIDdmU3V4NWpaZThXb3FyTzBCMGFP
            cVM2ZVVQMEFpdW5tWjh6SmRWRmhvM2cK7oBUiSxEQOU3wZGZVrRi26qvM2GaKi9r
            fjhnSdbYqkb9ULbcSEuQyoWIm0P94AzSmJsOzYfaP6GKJ/KD625Msw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T21:43:06Z"
    mac: ENC[AES256_GCM,data:9upFi9yR9PJ7sRdXqNJjmdFF35UUfqeePy7BKe4HP/Igh9l5Dmmr8lH6RgoI1MU1Mem+HUTI/ub3xixbHrj94nKhkDhk0nKdnOws5XFKpvP0c2iLTJLwUx9BnfHHD0rz5UFw/hpOSk+EbWLy++Bu5g2T0tmZ0cLcaa8SeHq0uW4=,iv:Zs1zRuwU99kq6m56pg5jxRcGxhUrLHy7RuIcGW33LAU=,tag:/sbgDM+IpxnXh3b5kR0++w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
