---
apiVersion: v1
kind: Service
metadata:
  name: comet
  namespace: stremio
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.57"
spec:
  type: LoadBalancer
  selector:
    app: comet
  ports:
    - name: http
      port: 8000
      targetPort: 8000
