#ENC[AES256_GCM,data:rCUD80FzEyF09l3O9M9/otvFhjDcvANmLUnDHvcgLIgTPsniqCAIVRas+m8=,iv:1kwytkbponer0ncK1YxBFFdsBkepv4cASGsxdQ46SsI=,tag:DIjhsq7O864/PTkf8YTuDw==,type:comment]
#ENC[AES256_GCM,data:h4r2vql2Fo7WC0MVcTrGlYSHfVeS7ShsVPo5zavQTvOY5TevqxRnlxd6ksb2zjEDVC/iJJdeVkIK,iv:anf8PjBlw8okK9tt30bIjnAJcSVBqAqI3ZtPzrisMDs=,tag:3vGZWV0plwGfbeaGlasr1Q==,type:comment]
#
#ENC[AES256_GCM,data:APgP9ewJMozDdDAuAvRtieGExEqtECtLFzIvIQHxpohF,iv:xUW+nnC3qc2oFjD9nEjPibS50KIfTF58iDYJq/k+H4g=,tag:GJ0IJba9Y24q6fd+VSSxgg==,type:comment]
#ENC[AES256_GCM,data:Yrg5qz0/mjv/fySUNi+EeXIvVjiq+67yM5h0byW2ji2rsqhgRkUlkiRB5EKe4PNLLHxHP4LgVXkEGG1C,iv:qSA0t8cWB9an6xwPmoYGbirCy0pCYD3rcjSY3TN/AdM=,tag:qFa+7Glsw+PNWapdMU9elQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:g1E=,iv:U1wcKe+cret1tCpVEay/eUQV03K24xMHwMfg0pMhK2c=,tag:DYeIOsPDxhr0Z9MthcKMTQ==,type:str]
kind: ENC[AES256_GCM,data:/iL5MzHH,iv:maxqKK4P0DE9pqunE+mq0w+RUBBshbvRsHXxhOVKh2s=,tag:IYCNH1PGlrknpCpWW3EaGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oJQiWcJHK3REgeVwDJfb,iv:VLVbwvVwRPgvdm7WkKvAlQXWzOzNTKi9SdE8ZI5Mnq0=,tag:UI4XRgTzw6qGC8soLEZJFg==,type:str]
    namespace: ENC[AES256_GCM,data:d+65LDl+SA==,iv:4/2ZZEvdZjNpKxSH1bCxqXeDappYphQ2e1PR9dfzUMg=,tag:akoMAib0o33TKj2TpREfmQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:TajhWTIJ2Lx+s4F5KtEADmeTrg8dBYCnADcz3lSTHSfBQzQVZcd0SzyH6a8jMsCFgg==,iv:TwKwGU7UIgN18odX8/KzHnQacuXVnOOzuK7ujgeQUMA=,tag:lHnCXLTbRTbhRFKtWN4MqA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:pOmDj/jTy5QMIdNGITPoePEcTKbYe3Pvr+Cc+g0V74A=,iv:6UJlkPBapQSlvpoL0bMfReJ/NylHTr9Ue96k49gfalw=,tag:wqC4L8s/p1l6EGqJH/7tMg==,type:str]
    #ENC[AES256_GCM,data:FMX6A8yJegw65LzdlaesAiMJyYv+38aJXaagZqaVvw==,iv:WZGvgTJcMJyqPeaDlJ3WWhL1dqfgDJUyHveVcIDAHSw=,tag:Nc17yBnon7vXAFBNEMCZ/A==,type:comment]
    proxy-password: ENC[AES256_GCM,data:dupI2o8RG9c9KQKJbEgVkS8SoJWsSEh3RrLf7r9Mn2k=,iv:6al6ctnU64jCMqU9jXwJ8D3BHdAmbPJCwd7swXJXtto=,tag:qg9WEVasINtpycPXz5d4Ww==,type:str]
    #ENC[AES256_GCM,data:k9bu/3bsOr1Tw/HNJQzD5JUT06vAIc7C8Hz0tbc+VlJiHyp4Wbly2zruzxzBtl7Kxw6cOzNqAC7XqAg=,iv:4gGCtDR2i4/RbsjypxfpibtiVjuVwCdNg+7HslHtfZ4=,tag:lTdOZRZbD6/kzhXa4J1KWw==,type:comment]
    prowlarr-api-key: ENC[AES256_GCM,data:YhdX7EI+BB+y7gyfoRQngcFrsYPnl4s/tevaXzqw8JM=,iv:+cssygVzHWGfXKYpqlc/IdngljWJX1S1S0OnQ7KyqQ8=,tag:oSPSeptCY0dOR6WNs8Zk9g==,type:str]
    #ENC[AES256_GCM,data:1DVGfL7Wm1JApCr68SyOkPCqZznINirtaYyJT03oDw6NHt2s5q5U5CcHqsIEh9S7zA1YadP7,iv:o3S1NmTGxzVBnk2if0+G0Za63koBcCt/0bLGRO1P6qw=,tag:dGDM4baCBfRB5j4KwZvkjg==,type:comment]
    torbox-api-key: ENC[AES256_GCM,data:U1HL39vhUvQSXbaidfpyU1aWeGAZ1rOl5eOt48JrVztIhyWP,iv:13yIsPihW+ZMpVfMRkXblkCcJQ5S4dXXt+9h/Nk4n/I=,tag:LiO03ZzYNLDDHIdsXDC14A==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TU51UkpXRUlKb0d0WkRP
            dUdxTHJUcUN1TmQwSWpiU2JZaXhxK3FGc3dNCndGVVRYaWN2WkJydEFabm5UTjdE
            YkhpcFRtTFlYYVEvU0xydEpRVEdGWEUKLS0tIGl5Ujc4NkI1eElTUGhEWHBHZDcz
            QzFUVitHVThVbzdBYS9Xc1kwMG5YMFkK0X9nGfRPkmDJIRVsxETwF1djBagOHtK9
            f9AgT2xVjyvnYxDAVKQZ+SsE5+BTdu5ZnG5NFaRJ0XWRowJ8iI394A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bzdrWHV6b2pCWFlJSUdt
            ZSt3dnFhR0dGMFUxVXc4dTg3amhWZ2h4NXd3ClF2N1pnNFhqaFIwZkcvNSswWnNx
            ek5GSEdXZTZEeHBFMVFHNWRzYURPOTgKLS0tIFZYZ0w4STcwOE1PL2RLTlhkY0Rj
            NG12aERndko5Nk9QcjVkMU1HRGo3S0EK8PaWbLXUKGV7puq0Gqrdj4OYNX/1g7ae
            ymIjASx+ghjURQVrB8XRNIKc2Ags9JOM5eLihh064YlLo872Jxwqug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UE5TMjI0SkxwMlM0ZzdB
            QWFjcktYN2ZkNUFRK1BXZzFSZHZZM1RSUW5JClZicndOS2VQSGd0ejJjM003K3BP
            Q2JZQ0RCMlJmeFpBSUlHZ3IyTDhlTTgKLS0tIHVDQklRTEU2cFBCczZlZERJNHlK
            WWZBRXVPSmFQYjRSMTEzR1l3Q2ZkQjAKdTBL+r/UhHqwr/5dAyWwQNkhiURz4Dxx
            8jWPRWEeBV36idYR+9pYPu/3fawXRbS91V7CbtP7KyOLLbObv2cjMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMVUzWFY1NTk1OUNLQTdU
            Z2xXZUUva2JhdnhJVW5FM2xkMzliZzNZY2tvClhENHk5dFlUd1BNb1hVenVveFpo
            QzhNN0FFSFVHOVMwYmY3SW9MejZJUG8KLS0tIDNiYVNGTjBzQjNQOW1uaVdmZ2xk
            dGs0TXRldGFraTM0dE5NSkVBV1dwZ0UKRkDipISpfqfUqgdcO51A0EP3s8oXf2oD
            Ren4N1T8rP36OdcyfLf5I2SOQ0XbyJ5Sk8Co88TQokjzx3pVJkyrzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:48:13Z"
    mac: ENC[AES256_GCM,data:2bvyRdNtG8SqNhYVVpH17nKzkJpjiEva6QiJSOJ7HpV9mPZ908LyRg/+ZmPUBtGtChOoD+4KTFAQHL5mmX2qiK3u8iBvXfGyRleU4ogzVNziw/XcO/o06tRgcbpTEJxfCg5yA72W0T357PhupiUf5prlTFUjDw38US/Hmru4DK8=,iv:JZhSRBvnTM5A3AnXq3+uc5iCK+ajIY4xOSD5zPOANBQ=,tag:UCjseWqvLcMi3iYDzdYWeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
