---
apiVersion: v1
kind: Service
metadata:
  name: stremio-server
  namespace: stremio
  labels:
    app: stremio-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.58"
spec:
  type: LoadBalancer
  selector:
    app: stremio-server
  ports:
    - name: http
      port: 11470
      targetPort: 11470
    - name: https
      port: 12470
      targetPort: 12470
