all:
  children:
    proxmox:
      hosts:
        rohan:
          ansible_host: 192.168.1.24
          ansible_user: root
          has_nvidia_gpu: true
        gondor:
          ansible_host: 192.168.1.20
          ansible_user: root
          has_nvidia_gpu: false
        the-shire:
          ansible_host: 192.168.1.23
          ansible_user: root
          has_nvidia_gpu: false
