---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: adguard
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "AdGuard"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "adguard-home.png"
    gethomepage.dev/description: "DNS & Ad Blocking"
    gethomepage.dev/href: "https://adguard.lan"
    gethomepage.dev/pod-selector: "app=adguard-home"
    gethomepage.dev/siteMonitor: "http://adguard-web.adguard.svc:80"
    gethomepage.dev/widget.type: "adguard"
    gethomepage.dev/widget.url: "http://adguard-web.adguard.svc:80"
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`adguard.lan`)
      kind: Rule
      services:
        - name: adguard-web
          port: 80
