---
# Allow all ingress to AdGuard (DNS server needs to be accessible from everywhere)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-adguard-ingress
  namespace: adguard
spec:
  podSelector:
    matchLabels:
      app: adguard-home
  policyTypes:
    - Ingress
  ingress:
    - {} # Allow all ingress
