---
# Override the helm chart's NodePort DoT service with LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dot
  namespace: adguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.56"
  labels:
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
  ports:
    - name: dot
      port: 853
      targetPort: dot
      protocol: TCP
