apiVersion: v1
kind: Secret
metadata:
    name: k8sgpt-ai-secret
    namespace: k8sgpt
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:jwCqiUDx84ziYh8VHz7hJ4N/whJpjqXWVCLhfjYlY91q0yusQ2KTcY/I,iv:wgXMoCZzofZjO1mUfZuahtYeeyy09+wGf3tvfJpi76A=,tag:31Fwvb3x/lqXBmma/FT+PA==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRmNpenR1WWkzaWM5ZXZm
            ZGMwZDhOdG93WnEvVDdLNFdaZEMzZnBPeGpBCmNrV1EwcXdLQzlqZjBxckxkeFJ5
            dksyeGQxYS9hcGlKSzZFa2p6TUdGd3cKLS0tIDhaSFBLR3kwZ1ovVHJvazdaN3p2
            c0tpYWEwVDIremtWbXF6cWhoUlJLR0EKaOQfZz02d0zO0UEUpRQJKrdOC7ZyLS4Q
            4Ov6bw+P0gs6XVgKfyDthDUej7shA9nCyIC4NYOYANYcg5L/1wtZxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXNIdHM2Z2Vac1NEODAz
            SzkxSklmMFpweldabkFiQ2NOMGZaRWh4aFhvClJRU2ZmMDZOejdhRElsMnlFTmlk
            anptQnpZczZDelVBcFZGeENZZjJDVzgKLS0tIGkvd1pHcXoyL2FJZWt0cVdLaWp1
            SUtaQVJoZTVid0o3KzFPOEozNkpUMUEKKbDKvw04ouqNFFokKLnm6ZvlGvE7zZRX
            dxF4Fpc4gSC0aPLgJwmIhQNS7XcTniurunjGyCy4VSGrsKop02+7sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcytZdTB5VHFJTXJNb0VL
            UEtZTkJiZitBcEN4NE1jT01memJHamVDUlVFCkpkY2k4VjkzL013SWczM0sydVFq
            Tm1vSkNWYlA3TVYySWxCbHB3V3pXMXcKLS0tIDRoRlFLT2NsYVhjODdtY1AxWTNC
            QnNORE9mUFVLU0k3bjk1MnBVTUxSZzgKAG0enknjnud9NBvdpdeKxk2uD+RPr6W1
            Wb8mCo5KdmOsrGWhnKON3RbhpsofdyJ+A4cD+hmsh3lhKxvJfqoKzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWlRXL0JWM3djRU9EQk9X
            V1J5STduLzNCMENaSmpRRVBRdWhldGVVWFdNClZHamVtbXFiZ25hNnZoMjNESDRE
            TndhRmhyMzNaM3RieHRqOThlaThzdkkKLS0tIENWQVpNaCtLV3cybFNBaTZONHJB
            am4yQWlUQXNmeUYwWnBKM2l5bUFhMTAK4v4ZXcgFsFM//+SpqsLMdwdHay3cRmPP
            p2FU54t12vS0zKs3F+/qd4DuYclKlCx5cQFQkEzNKWPQchDI8mq6xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T00:42:36Z"
    mac: ENC[AES256_GCM,data:S1DFirSdCZ2ZdoLAiOLXoCoaUqQdatJKhloR1wp0Ep2gSZ/8qLIb+H9kRuNDmZ/EqKwvK0SWuEn8yShacy3jtHM9l8O0rFnDgViklXNPi+OPjwjtZ2AyxxrmALWVj5ZkNigj4LpD8d/iU31asb6QBZIuwCeFu4h41pYhLfzgQAo=,iv:HIjF/NO8rcTuNZIo7r6a2rKALdLTKfHtbtbv2RrKNcM=,tag:0H5blPcNsw5KznY+NG0kgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
