apiVersion: v1
kind: Secret
metadata:
    name: persona-mcp-secrets
    namespace: persona-mcp
stringData:
    openai-api-key: ENC[AES256_GCM,data:sjl1cNzrC4NfRE6IataPOzaXbWq/8KJXejG2qfwZuiQV6zGYMFLV8FH1,iv:mlbcspzFJP6aV7WEaI4MfU78uwn8LSGOTA7Mj4uPmhw=,tag:4o5pyg+cPsN+rpuxzkS65Q==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZclRmSmxWMjlucHNZN0Fr
            WHZieW91YlJlM25DNlpyaEh3Z2xmZVQzYUZvCnhiSGx4cTZwcTltVjlZUHJQVk1O
            d2UybGllZmVSNG9oTTBQQ1NIZEpmUGcKLS0tIEk1N2daUm1kQlZXSkpqRHRSMGFm
            RkUyQmI3YXh2aUZJd0x1dUxCc21EbHcKOEYPd8FCJ5YnNh3paaV1M/MvV1fAOpZy
            8NZYV9Y136kantpDSz1mgBKXT62WcQQNdnx9/QsQRscu4TPEvwM4HQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aTQ5UmpaeVErN3lIei9q
            bGhETFBDWTQ3K2liOHo1U2hHNkJVbDFLTEdZCmhHU1dSdXRtQk5XUVhLM0d3VzU5
            aTN6bGEra3h1V0k4VlM3aUNHTk1GcHMKLS0tIDJXZEZJYXMyd3d5SlBMK3lxNDlm
            b3ZMZlp3MHVoK25PZXZGRVFicWN2SGMKR0hc2caXtBS1DLUrwC8CEtDSQiQuAFZM
            OI5gVDP6TLRmrJPcS6lolU0KzXPoYAzBlGP6AFkB2Qklf4dgJ7SkXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYTFkVERVVlgxRnBJMHB1
            S1MzM0EzRnFNNHo1bUU1YWpIYmFFaHh6Y25vCnJ4RGp0YSsrcGFoNW52Z3FOSU56
            bklBdVdNOGJGSUNRZlBjZGZjQm9waWcKLS0tIGZJZXVMVUxEMEswRjA3ZTRFZGRw
            OU5xOS9MWG1xZE9QYS9iMHJNRU5ITzAKQ//Qn7+3kO2vN7+HdoqT8o7zGM/mDF+Z
            gLDLgGTHtS9ShvvyoPA8cdU9WDFXOcARgbYcdPWDizS2c5YTu1ySaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY0VIVVJ2WkNLemxqd2hB
            SnFzRkc3S3J5ajkySEh3S2dSMnh4bXVLN0drCk5NRkxNWm1OL0U5K2hQbHBsQmxt
            Z01GNzNjdk04bFdHRDR5VVl6VXVyZ3MKLS0tIEZLcmRtUUZpcFhWeVowNlBES0tt
            L2VJQ2o1dGw2MUJqeHRUOXpuTW9RVEUKiihFhlHKtTQZ1tZLrGUfllZrPxCu4Mb0
            kVghdGF/jOW/W+soq5fxlWIKW5l6sNNrcHTI3BdH4I4k3MxHERhrCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T02:38:12Z"
    mac: ENC[AES256_GCM,data:fLun0CsEF+kneS4KCpadxnpEgZ5syxdVpZJdU83RXtNj99q+dcNuzZEpb3QxQ8Z9aipht+z6necw31Aj3UF61RuucmPv5JZ6yZbYKEHv7HVkZfFpO0d4Hld+nix7N92qiRbl/I2kwYUF1zinc7cwPmsWwnmH/KiY9AdslnxKbQ0=,iv:cQSIK8omTdJD1CvmjxIisPAWcGjt54qTd/oT9Z89FE0=,tag:1qFR0KAkm9hemqs7mVFzAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
