---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Immich"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "immich.png"
    gethomepage.dev/description: "Photo & Video Management"
    gethomepage.dev/href: "https://immich.dimensiondoor.xyz"
    gethomepage.dev/siteMonitor: "http://immich-external.immich.svc:2283"
    gethomepage.dev/widget.type: "immich"
    gethomepage.dev/widget.url: "http://immich-external.immich.svc:2283"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
    gethomepage.dev/widget.version: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.dimensiondoor.xyz`)
      kind: Rule
      services:
        - name: immich-external
          port: 2283
  tls:
    secretName: immich-tls
