---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - ml-cache-pvc.yaml
  - postgres-secret.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
