apiVersion: ENC[AES256_GCM,data:O2U=,iv:opzv6nz+5llQ1QaFaRuB7i0Pc5BYSODMC6XAy17mVS8=,tag:d8pMkawuYtkKaOV4uzDiXw==,type:str]
kind: ENC[AES256_GCM,data:svaGsBP0,iv:DagkS/4ZEK6J9Fd7kuofppx05eZhcmItq3AOvl58rdw=,tag:nVjojmbajurenvmf3m7r4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mk8nRS82m9o0IO1QID01,iv:juZp7BqehZ+gAujNtdIdvL4nV5imrELQ9Zhw1hHhBQ0=,tag:eGPa3MycKa5ZJk1VFJDTZg==,type:str]
    namespace: ENC[AES256_GCM,data:sekNRo+4,iv:q9o9d+3AxnatjSUosSSrixAOOTGdkXqlClfiRxz3FSM=,tag:l37gMopQS2T7lML1C3DPnQ==,type:str]
type: ENC[AES256_GCM,data:4iWWtHjQ,iv:UtW33AJ70NE60bLpuKUah2gGc/VvXYulfSj7TSKQWEo=,tag:Sfsjiy+uob+8FrJAdN8Giw==,type:str]
stringData:
    #ENC[AES256_GCM,data:Q1/ydWwhQokBregT97qqPoo38muf9eCjXcXskCT3oYLT,iv:KIQ9CcBXL57Zmasq6gJo1+KxJ8yMoq32d35qaf2ZYCI=,tag:9dPLt0cJriEyzEsN31GugQ==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:e/7hSKTIA64=,iv:yIbE8K5vjVQ9DVnEVSRDdK9pXPoVecU3yAepfABExJM=,tag:poTBsi+sap8U3jFh6qkREw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p7FloRPWiTKfqwqvTyHfZlgcW5uh1pfcJcyRPw3A7lMmy7OCxhUMXdpMuBY=,iv:BAMIZnxdBtFEKB3/1NffRFVHISucsBdqdf8wBVSjcYU=,tag:UTORlQigmWQt3Mt0VRds1g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:WhYZ5Iel,iv:sn7gykmuwLYHte1qHdrQ571dbUlKLGT642tX3AjLK5o=,tag:c1BqVu9MhuWaeQRWkbpefQ==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRDZMdlFyU01EWWQxQTNx
            ZlN6RTQvdmZPZ04xMmVXdU1CaWRka2dYMkNzCkZ0TmRnNndVSm8xYmxrV2ZDQ2pU
            UWtYaGN4bmltaTZCUG0ydDFveFBkTEEKLS0tIFVvQlB4QzdEWXFNeDB5OElGZHBm
            RXRVdHJ1WHVRSWFJRG14R3lrT1BWNGcKW20xtvu43fR/vfqO+19EIvntKfYzsYUN
            touZKG14aVTkxjIa+upTlq2nnXXTBxNqqRfChWA6o7+PYVQxRR6ymQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dDhMOGhRekN5bkpoaDgw
            MitqTkVCeFZpemdWQnk4Y1NhV0dwRDBJQldZCkJTK1JQalU0Q0x5d2oyNTd1WUVo
            UnpZejBJcEdjSFRsOHNNV3d3RytmNkEKLS0tIExkMnIySDhNcmVkZjNjamtFRFJy
            VzhFQ2djMTJTejhFaS9WVytoRVNHVmcKnGaXvL+KoMn+P1lfErTxdFUGYoc5aqgP
            Xv2Y3Lhn0RhxAV+uQqifaJ0CIsX5MlQ6eODJB264k0XK1cNHXN3tJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT0xkaXpiSU9LYnlUU1hG
            WWk0cjdVQ00wcUJuTGxIbGFROEgrWk05NFcwCjV6azJtMmhqNXIxNVJDN01wQy8r
            b0lUYUZWRU1zOWlJSWpJTEpUaUZGRUkKLS0tIEFsa3V3WEc4SGRhekhSekRlWlVR
            R1dMb3pFempnQUFRbXhWQzIranMxbFEKnH6hsr3uVhmHFutFvGDxwcxXuMCvTeG/
            XSCtWIrr6AnECAWO2idk6/VpVmU3VxTU2VA6ccFa+E6uEWJlrgr92g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUXZQQWFuMm5KdFVVVDBV
            cnhPRFoveGRyMGxNTEFzUUxGMzBhUmpLaW1NClgyK0NFNEMxRE1zTWQ2VlJwNEpH
            V2V5Ym5aM1g0bjhYV0Q4QWsrL2w3OHMKLS0tIGtlVzhmWnZNYll2Q1VERTBBd0xH
            ZnYyeDBUdDVhV1hsbC85aHJoWEt5ODAKjnJ65EFKm7be1LTxDadPijtpnSbQW8fz
            yyqzdgyH6iMqPKtli3+GmzGOFZgl8SxjPviQeFIR/WtgxkzSL7nk3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:54:41Z"
    mac: ENC[AES256_GCM,data:Cwy7JhnRz0R7v2HJWbBH6/A6/E5tURhYwe66eapIvoZp5heV/nBr/PdWcnL5DEQ1YLgrU6pWyFquZkHWNfq8Pz2bnJj94TmQoLpKdVnyowyAp7mxIQhGIJMIl9PPXquhFcG1Wj3Z5WFtjIyDeRDBrTkMLp+ilthvnoWQcTUz/30=,iv:CdD3uaJKlenampk/lhYegDCLqieVub9pnWSIdW2AXpc=,tag:qkRqEAA3BHYV34dPJPgRLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
