---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
  namespace: immich
type: Opaque
stringData:
  POSTGRES_USER: immich
  POSTGRES_PASSWORD: immich-postgres-password
  POSTGRES_DB: immich
