---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: attic-tls
  namespace: attic
spec:
  secretName: attic-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - attic.dimensiondoor.xyz
