---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: attic
  namespace: attic
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Attic"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "nix.png"
    gethomepage.dev/description: "Nix Binary Cache"
    gethomepage.dev/href: "https://attic.dimensiondoor.xyz"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`attic.dimensiondoor.xyz`)
      kind: Rule
      services:
        - name: attic-external
          port: 8080
  tls:
    secretName: attic-tls
