---
- name: Restart nut-server
  ansible.builtin.systemd:
    name: nut-server
    state: restarted
    daemon_reload: true

- name: Restart nut-monitor
  ansible.builtin.systemd:
    name: nut-monitor
    state: restarted
    daemon_reload: true
