apiVersion: ENC[AES256_GCM,data:i1A=,iv:8NNlhiYrUp/gXXyLVGFxk4ygLLmdjbtgtMtxmkv2Gig=,tag:IwDXHJEaFHTzKLqTj5VMAA==,type:str]
kind: ENC[AES256_GCM,data:YEjt9Ks/,iv:QAsvvE63fBU1uZdE5OwUlJL7eS1smoH0Oyh3jMWiIJ4=,tag:ixG3+4SnEZOGf58SS1+06g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uoq2x0xL9w3J57tmAsGPJA==,iv:ssArbBl0LAHxYtBfikOQQK9/aT6RgWmZhzmjf7iDLR0=,tag:SBUBI8CjUwvEVYZsJJNtTQ==,type:str]
    namespace: ENC[AES256_GCM,data:psMWpOYqISk=,iv:3RvbxDpOLjjaEXVYF2/z5eHBZ7jaPOK/tfKdqsn7mSE=,tag:bY3w0T/8QhDyBC0t7iXrhQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:sAO1YgQi+qaVmpnx1erQ5qLyxZVKK01Rw+FvKZI02QmKBCsFYzO9PERmDd8u1IA=,iv:BIoA4rAIQ+CWVUMuqmxCtL+hc7vc8ardSHHEAGsa0xQ=,tag:lQKEIZUKSeB+kBD5j5/LTA==,type:comment]
    HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:7QocWPc=,iv:K95NXj7YWCPDHaBt6p7m5a/we2S74r2Jd7Pd1DjZg+I=,tag:NDUHCGWFvrjKF/grT/uYAQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:1Byf33TxzEEpVzsjJGE77gBa7Ro=,iv:iIc98aQL1SYGP4pMbVSdoY9k2/I9BoES3YmU0DSuXQc=,tag:47YgFwsLdmFO5L2bvz/IzQ==,type:str]
    #ENC[AES256_GCM,data:mha9zsy+hsAiUAWEu9Np+DoL,iv:b4pagp8bcCG9V49BZztc6d41kDMc/0BFmEBjwsyGtrA=,tag:JrHm/Fpdw5qrPQpuOLFr5Q==,type:comment]
    #ENC[AES256_GCM,data:9yQXuw2G9qF4UqO8eZpFRYOKk9qPYWB0DOA6HLNAegJt4gmhaWcNpYLCTRO2jNbdtewUS1gm2Eg8RFVVsJ52QqkgnZRR/y6c5LEJJKXLrGF0e5DLhtpgzlcNaV5RYUWUi2c5SkN4dVMHKBrJDw==,iv:IOtT4Ap9WexmNF/K8i5gqCHbSUa/lw4ieG4YOJj+Eag=,tag:oyJ+kQDliXRSEHellg0HWQ==,type:comment]
    HOMEPAGE_VAR_HEADSCALE_KEY: ENC[AES256_GCM,data:g4YEMErmU787f0H3zCa/qO4cljW4u7vqcJ/eSX8taYBMYq4Z/r658Q==,iv:8toxnKLKfI2hn3suk5MncvI6s7saOVcsYJUmr9L50Nk=,tag:vVU70NmGEJHCU7YrpYgFng==,type:str]
    #ENC[AES256_GCM,data:eWCOgMZF4oDfFE21fIaI,iv:InUGw0iOo4NgGOWrPNJprlpR+01xhjcXlCjCVjMzne4=,tag:qh4La3pdF+NpvF8MQypk2Q==,type:comment]
    #ENC[AES256_GCM,data:kZwktq5jTLUa9EUeDSiu7sMo2NdiZp5pTlT3aCiXR8XozXa3ek1Pc1eZWjsvNxrseuiZ7LoH+YpFgx4M9aQfchKd0uDI12dMSg62,iv:IrcaNIOF5eE/bNwYEc2j73pN+/s6tVXgWWCc6hbhwUk=,tag:mRtGYsGtczbO8bAGPZYt4w==,type:comment]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:3OB5m2dL1pwT0qdxP08ZL60Xhxu/aM+G4jdx+8QVAvLXUacZW16T3PdZ,iv:BVtXjhOppc47Ugq8I11H+jvkqzhMKvC3gr7KGETBX08=,tag:6SAqDfli9cMEVORiFVVSlg==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZVlDaGF2ZFkxTlRMWG9r
            cWNmaVlYTGJzelFCckg5RDJCV0ppQkZZZWdBCmVJdW5MV0kwdnBvUmdXRkhPc2Rs
            SGkrZ3Z4T00vMGNPdUxVaVlBaXVnQW8KLS0tIHNPRjJPOWVMSmIrTTFiOFNCMHRY
            Ry9qYW9RTUpaWkY2NCtiaHkyNDhZbEEK44NrvgiYJOn8MsqRVb/XJMNApy/zom/X
            +f9prJVnXRG1+y1G6FmI15KN1y1E1aXJSCOVTq1VZNdGitGYuUc93w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOclR3OXlsK3lISW5XUUh6
            VWV4dWs3RmFoUGhQQmN3bWVjRzlpZ204Z24wCnRkR2RGYzlENTFWSXM5em0zaDdI
            R3pSUEJoemhZNEt5NmtuWlJoanRodlEKLS0tIG02ZjlaOUJudVNkbDErK0JiRnhH
            TVlScUNiM1U4OXovVUkwRlVrak50WGcKr2WBgeLcKBfeATe9e/Bbwp98TLO7BULw
            fVFGzvszfOruOXdTbwnhskJss1mKyjVen7Bh4zb7cRpebHuQjk8/dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdEhsaHhoWFZLdkZYaENJ
            WnBlSGtncXhlVFpvSFpUdjM0ZUtaNTlQNVRVCkRMd3FBdHdZa2xmVk1tNldWemRh
            T2RWYW1LSmd0RU1yNVE3bFdLb3AzcUEKLS0tIGM1WnR3VU5GWGlKTDA1T0NpVURV
            Z3ZMRE1DSm1HQmM4YWZYL3Z2Y2NUUTQKm9pLDo+s38pW6QniYx93sp4X9Jtrpi8D
            SrKWSCJF1gLoFxfirH1uv64vtEVK81/z69ioBnWGzQOM62/Dze6/yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR3ZHTEVRaHRnOHkvQ0pC
            TG9PSXgwVjBTMXQzRFdNaUdRdEtQamVIQ0NnCndDemlDMHU0aEtxT1RSUjZkWkJY
            V0x1dTZOcXgvc1pRbi9WSG1tMTI0NTAKLS0tIEsydFZZOHVvOVd3TWRjcUtNOWxB
            UytENE12d3ZLek5PaWtQZGs2OW8ybHcK7iFNydpU7FCdZeH44Q3MLFztClPEGjLn
            llcEzO9NT7UOsVI2hIx6/6oa3hI3KQSMcNnqBgcyOEL6gnN22A/x6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T23:12:43Z"
    mac: ENC[AES256_GCM,data:Iro5vE9gz8nDzKl99mDnIiszWkUndlogkHbkElMgqyzbfPz0882Nzqea/mjl7QW0BvzLJvtmq+xDZZudAFgIyZzyzvKldkYPI9e3E2A7pvkGU07e7tDLwkwYuyA8GoJfyRm5gbMMQve6iJyVnfdF3dDZLHXD5OOPhKgQUccWwdQ=,iv:/uHdZiqLrmMgMWsR1bbad3lHbyjcBtyzVj5rEsAkNhc=,tag:3qkzsrOOSjmfUe19yGbzGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
