apiVersion: ENC[AES256_GCM,data:PKU=,iv:ONXAJuPuNc1biRp+hEYD0Kt9PMS4S2suCMU2P2BFEww=,tag:NYccjbtF7DqdCRzX6a8hUg==,type:str]
kind: ENC[AES256_GCM,data:6llIHVe2,iv:3UY8Ok7iaTqpLV7BH6nbXrN85vMu2mQWObUIehUu/FU=,tag:S2fAOBi3Ty9TdvzNyTK2WA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6RUSHKB7uQRe/UXPkMIIxg==,iv:SuL2k+5q7H3bf1LUTts68MABeoGj1gXYdquxcVTV97o=,tag:kDBDfqv6lrD4ycFW6TpFQg==,type:str]
    namespace: ENC[AES256_GCM,data:OiutpgVwP9w=,iv:2LwpsfaKMCeqs/WTwFGZ+ZnWp5KC9uMhUtjsb7F9oOo=,tag:AR9jvKlnpU7+SCC8QomFRw==,type:str]
stringData:
    #ENC[AES256_GCM,data:1BkxCrV5lHhT+q5soNminZPXSl+ZEO9dt1K/Xggqxj+lCO5x6J16dQ==,iv:0CTwnxGAaFOtDf54LJZQlS+hctXnUv+Zth0J5e7CacM=,tag:/GlCBGPhQ3Lj4Ktca++1Fg==,type:comment]
    #ENC[AES256_GCM,data:67B/C34GOuYEvvbMrZYyA5BZOOK6uOlpMdf/tzSebz0ud1xs,iv:eSlg5R3jurVBzmGIYcYldLG5Y6KQVeeCQT+ARrqD02k=,tag:Ac29arW8L7Ntwe9jNp052A==,type:comment]
    api-key: ENC[AES256_GCM,data:lGR616zB6XFoATMRUQZ5JaK/4g0wGDTon7jclCeLG0G3KdX4Vj7huK1p/B95B2m9NqhwJj3HUx9+jI+VZ/wMuQ==,iv:pBJ1gFkr6oo9ORmU27clj+4pxZ31o2JLjRJyYpu7ah4=,tag:fm8bggoTbZYo1gl5vIF5pA==,type:str]
    #ENC[AES256_GCM,data:/zSSF8byewnvN33kEJLKFWu9F09ULg8NRNZB+Gg3nhc=,iv:tEiL3p82jycOKTICOrNxrD0tQovVjuQTzr3Q+UaMvoE=,tag:Gs3qY5XXVli5qP7UKKx1yA==,type:comment]
    #ENC[AES256_GCM,data:67B/C34GOuYEvvbMrZYyA5BZOOK6uOlpMdf/tzSebz0ud1xs,iv:eSlg5R3jurVBzmGIYcYldLG5Y6KQVeeCQT+ARrqD02k=,tag:Ac29arW8L7Ntwe9jNp052A==,type:comment]
    management-secret: ENC[AES256_GCM,data:TBe2qDHU9wSqBpze7Zi9BY/0S1t4krnwAvjw9sYum3l1mtPPysaLwp96SSum+TngjJDZZeWVjPfCFLu0iY9zyw==,iv:OhKtXsCXB6nCCJ6CuDSPQpepeNT5HyBHEp9qHuvYyYc=,tag:M/QL3tYmyet4sWmf2XFEfw==,type:str]
    #ENC[AES256_GCM,data:0D2IqzWxPbppytK1D9k/ha/OyIVwrCMT3is=,iv:QP8gh3eaPU+QXA4yiqIFsbraZKSIHZ/2ah2Z2ifS7zs=,tag:mIJLhFqrzWyrzZKaCoBPtg==,type:comment]
    management-password: ENC[AES256_GCM,data:vTujmkECAz+M2FfqcPgK6GNv9bmZL+zmuaNws+g0lXjYmoD7CUno6BbfWj46fs3fNfPSMucafK06VMUNKS4Leg==,iv:2/NloehzSQkyO7+f84a+fdW4Ogv4bLKLQYdXFo+BjkA=,tag:cNlZXG3PgGJnLja6GskrLQ==,type:str]
    kimi-key: ENC[AES256_GCM,data:OQPGufQU5WER/RtDn79eJ9j7s5Jd+0mqN+o43cfkoB2p4uwSsS8/wnAcdCP2kpjXWsFC/K6kzs2lbIHb9oF3UaDTd6kKAebv,iv:B61ND63oeL+fvfVSjMxnAM7SXtjxLVSXM2X876zsndg=,tag:SPgvRYStLNfxw+CxT4JRww==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K2NBTUtMekUwU1cxckRP
            WlhJdmxZQ0FTQVZCaXRTemlncitOVG1kblVRCjJ6b0lGK3BTZTN5UDJhWHQ2ZlFU
            T3dqVlhMTFpBWnhZTVVWaWZaNUhQQ0kKLS0tIDdNTk9tYkNkY0YyNmNkZFcrYkRr
            TlJHZ3dGSWh2UzRHa1pOeEpObDQ1ZE0KJ6LFgozulGFLOtiH3jy1VE0FCRFlE2yX
            m8qeKD4MEZ/OqGQE/E7SY6Q0oO22mPlAdQuuMFYYQqKGF7DG1hitnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWRuM2ROaE11VFBIaHpy
            cnJ6dlBWUWg1Njh5bzVYcE1hYS9kTWpGYmxrClJUZnNtS2t5b05LSmtIQkpxeVZi
            azR0Z1I0bVd1OHMxaUZVYVZTWXlrY1kKLS0tIG9oWUxBNkpPS2dTT3hmTmlGekVL
            TEFyODhqU1RBeGx1QTNmZ3hTaUFZenMKFjpdDaagKfn4FA9Xcqc90ce1KWRxyieU
            60RYaNF7TP6L4Ny5/5NPoc9GcreEqwQ8Oow2oIUPxxI3/H9rWnRkZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY0xrNE5NRXd1ZVN2cFFi
            UzlGQzZiVWxQaUV6RzJEMHY5dGVLcVB0U3lZClF3T1NRd3Z0SDNuZnZnaWNBUUpD
            WFFMZmZMR2VTaHE1QU11SXpwSWdIUWMKLS0tIHR2aHc3S25RTUkzdHU1VHFVR0Zk
            VTBla0RVeEJEWXdOQ085K0E2ZkNpcjQKIbPi4ebLi4S6bOgzXPJaBjSfirL/WeYN
            xganBo3eik4jmfa0rsfW2NicxW27G86A20BK9OaUYlDWBefgfK2h5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRlVZdmxHTWw5OEE5V2tE
            clZKZnJrME1mZVY4K2daWHo0NnlaMGxiZkdVCmNSV0ZJQ0E0b2ZOcUVBRmlZMnpJ
            Z242UjNFaTJkMjViV0hHbEgvVjF5STQKLS0tIGtORUhmUWthUk9ZWnpRbllsTnBq
            Tk1FRFRtSGN1eXEwemp3eE8xbGt0Y28KFmYovB5Q/ef20HHOD/BuNXg9Cqxl5zfr
            dstS3XS0OovbJ2PbST+s6pcvPWlwzgxnZjTEu4asUwvrZUkX4Q504w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T08:13:52Z"
    mac: ENC[AES256_GCM,data:HoMFJFgxcGyGmJtqGQX5CPkP2P+04YlrU0L3nGpMOWCTNelJmWn7iLJ3L+89o9LATPiqpFIeUqqh+7t8ciYvGlcmBtPeOvPGF7CbpaZyIk24DJmE9f/en18RUYCgr5MVBw37GcCPxkfmUBn5D2MA9xBujvzprnxFIS4fqZ7A7vg=,iv:0eblBrBShVRu8Zmk8ysIFPAqw5/F+tq/SAtL/Si+4qI=,tag:yRhoEbeJE/MdAxUJDt/VSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
