---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/group: "Smart Home"
    gethomepage.dev/icon: "home-assistant.png"
    gethomepage.dev/description: "Home Automation"
    gethomepage.dev/href: "https://ha.dimensiondoor.xyz"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.dimensiondoor.xyz`)
      kind: Rule
      services:
        - name: home-assistant-external
          port: 8123
  tls:
    secretName: home-assistant-tls
