---
apiVersion: v1
kind: Service
metadata:
  name: lobechat
  namespace: lobechat
spec:
  type: ClusterIP
  selector:
    app: lobechat
  ports:
    - name: http
      port: 3210
      targetPort: 3210
      protocol: TCP
