apiVersion: v1
kind: Secret
metadata:
    name: holmesgpt-ai-secret
    namespace: holmesgpt
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:vb/HhfvBSIILNS9WBEKvY7goBhCsQhKP2OTxf/b72oSkG2oqBjduKE8R,iv:AsxldE5HGTCjzXwPhD6vrMqgGlGBahdUkaluCikBqWs=,tag:hfaLdko5xVc74tZKBKAA/g==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNEN4a1RiR3A5WW1UTUl3
            YUVreFhvZEVYaytoQjA3Zm9FM0Z2UittT2dnCjllNVg0NWkvVGtuZHcwb003VUNC
            VnVZZGRIbFNrVkNTQXZYS3ZOY1V2Wm8KLS0tIHk5Y1pvbFJkbFhmZVBYM2RPZWZK
            Ly9uTG9uYjVPMVQzc3ZaQXh0SUxWSkkKKZvQrN7gsbqwAdSOrlJ6E0eX/Ha411GY
            IaREGM+fBkFujaUT+eBVuCJU0W1NiMCJahIl/JRkJoGFuJ+tFUoVXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWDJKTjNZVTcrSEFtYW41
            NklmQUd2UldCL2RqODRCcHB3THlmelJ1dHhjCnZvMVBoUWdsbjdIcUJ0VU9wSzhl
            V3d2b0YzemcvOGtvbzFaY2FXcGdSTXMKLS0tIFNJcGdKaEExcEZ4L1VRTUlzUHRy
            c2x3RDU1RHY2L3Z5TFVOVk8rVE0xYncKoaGa/cSfzBjau54aPktEex4a0PmZxe9o
            355vWQfGABCtghWXapWGYyY+rrWY177d4JwaoxgrEIjpGeCO9cm5EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEY2cGtvdG14a0Q1Vk9j
            ZDJaa05rRktzd01iT3Y0citDWDBhZEhYYVEwCmR4WTZMU2h1UGN3TGQ3T0g1M09x
            RUhNOXpYL1RQYUdFV2RHUzNJWURWdWcKLS0tIFg2UDFHVTQvRVY5U29LR010SHBl
            KzNDWW9TREtDUGxTeVlRWUdkZlFjZVEK2ng2zkZspoPvNfSvKfrh3IM3nO679sAg
            CXFh92QPeDwSD2h8RfsuebwFKV0s3zYnEUSppe8enoD1tFkhaNUWtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbWFIRnFjeVhzdlB5c1M2
            QjlETVNBNjh3TURTdlFUMUg3WUE0NlBIaUZJCjdjVVZtVzFRVDVyY0hGY1NSempO
            MC94dGFRUk5uclhrYllGZDdoREF5WnMKLS0tIDVHcGo0T0dGRk5qcFM4dk0xaG82
            c2t3NTYxcDE2UnhPR1hpQWsyUzdPYWMKIp48QgmCHYXbgGNXZ43fX3YD2d7h0XQs
            B659bFBOqIOgzKHEjpRbxT42B9PoS4quJdaV0guZ3m0aAgWq5dozMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T02:35:32Z"
    mac: ENC[AES256_GCM,data:T2GLA52X/63qlYukSb0ubJZfPfL6YoCfWT5CMd9ztxmo071fkOkfxO1J4sMVEKqkpHpz+dblb8LLUMoVwozvtY1A0d9tXh8fSBpkOPJaUHnULZuIWExgnUGXWPbfI2mBKWJqLLod4IN73iRSB7NigQz47MEt/cMvX2mT2H/rNrs=,iv:qgt/P3XNcw3LdhC4sEs8wMqh6exbm7YQw+d/TlqkP/w=,tag:fS1l+m3a3WuEf9IISrmWuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
