---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - attic
  - authentik
  - chromadb
  - cliproxy
  - forgejo
  - codeberg-runner
  - headscale
  - home-assistant
  - homepage
  - immich
  - ntfy
  - open-webui
  - voicemail-receiver
  - stremio
  - bifrost
  - lobechat
  - monitoring
  - renovate
  - clawdbot
  - zot
  - persona-mcp
  - holmesgpt
