---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - authentik
  - chromadb
  - forgejo
  - headscale
  - home-assistant
  - homepage
  - immich
  - open-webui
