---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - attic
  - authentik
  - chromadb
  - cliproxy
  - forgejo
  - headscale
  - home-assistant
  - homepage
  - immich
  - open-webui
  - scriberr
  - stremio
  - bifrost
  - renovate
