---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ntfy"
    gethomepage.dev/group: "Services"
    gethomepage.dev/icon: "ntfy.png"
    gethomepage.dev/href: "https://ntfy.dimensiondoor.xyz"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ntfy.dimensiondoor.xyz`) || Host(`ntfy.lan`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
  tls:
    secretName: ntfy-tls
