---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scriberr-tls
  namespace: scriberr
spec:
  secretName: scriberr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - scriberr.dimensiondoor.xyz
