---
# Headless service pointing to external Scriberr instance
apiVersion: v1
kind: Service
metadata:
  name: scriberr-external
  namespace: scriberr
spec:
  ports:
    - port: 8080
      targetPort: 8080
