site_name: Homelab Docs
docs_dir: content
theme:
  name: material

nav:
  - index.md
  - Postmortems: postmortems
  - ADRs: adrs
  - tags.md

plugins:
  - search
  - tags
  - awesome-pages

markdown_extensions:
  - meta
