apiVersion: v1
kind: Secret
metadata:
    name: clawdbot-secrets
    namespace: clawdbot
stringData:
    #ENC[AES256_GCM,data:tivVr7aJ0c7C0s+AtKzQsH4BYedaBL4iqegExgckqD2HcGOX8AIZEXg=,iv:50xzytiBf4pZ5gvXHUsAiQqpzn2axUDmDlel/p4rEfg=,tag:SMsewlRn42A3qDjfPjap7g==,type:comment]
    bifrost-api-key: ENC[AES256_GCM,data:ooa9J2V/Tiq9RTjDdyI+U00dCmDVgKIKWxR+LrIT9N11qq4GqGAmgKoq,iv:UV9Ob7LHspGntRvOSuI05G1DrcO0o2FeKLHWCL6ztVY=,tag:90MzI2bbVXI84sRItt5Mrw==,type:str]
    #ENC[AES256_GCM,data:tDNK4YQBHRvQp6dXgxnEkaT7BPvcKUKNrYAcD/kZD/D1/rocBkGBQzLX1Q==,iv:ug+YxYs7WkKyJkMZJ7ZBLl0KW6GKGG8+4fz7+Z8VKRM=,tag:JlS7HzkxGD+j0FaJ/ztuoA==,type:comment]
    telegram-bot-token: ENC[AES256_GCM,data:Crl+NFFntWJq4Kme+jWdFvIgbDYAj7Wz/ls2uUKBHBWkUIALtP1zXGmRxOLQjA==,iv:jSwdnz3RDoMp4+y89TtGrcRsGGB+9jK5i2UsQrr1J5g=,tag:Rtknwq+SUCPNQ6/Z/SxgZg==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSmxmSFUzVGNXdlBhWXhr
            bWlwc1B5Lzc0Q1dRWWVWaFkvZTZld0pBTmo4ClVaSmVNbkNCRFFDWHFkcERiTzRD
            MTIzZVhPOGc5RURxeGpmSUVjb1gvVkUKLS0tIHh6eFg2a2Q5d3hUTllmclVpTUdu
            OWI4d0VTeG81YVFKWHJRSnM5cmtoRWcKl/05a/Z6iszqqE826FxvIQ3OLI2C2HVb
            xVCMcarCK9X27so2baviSIKoclCkeLDm+OCDhZlNOj4xS0givz4XlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OEJxN0hnVkpzOWpXdzd5
            L0FURTdQcWd1ekxJVTZuTnluVzI0Si83S2o4CjBDdDM2SzJ5WjBkczNVenA4TURS
            YkZMWjFuVm5LNHFHTjZ5Qm1XaCtUZFEKLS0tIER6TFp6NmNKQmRWalJTMjFDb05i
            TnVaamtoZDZ2SXdSUGFxaG5Vb29ZYzQK6pma2SFPX+WTMU8CX+jZHnRRvyOL7jmS
            aVZAURHcXUaYvfz4RDwvmcLhvJBOPfZAY+pAyQ9Qu44vmNYAfrtXeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWTBMMkVRMkR6NzRTR3pQ
            eExLNm91RjhSejBxVEFKalZlN2g3WFVHdFJzCkFXZnMvMC9JWlVKMXExcEY4bkpL
            WHNJNTAzQVlaY2ZmR1VlVEkvbDcyeHcKLS0tIDd6blJNSDhoa1RxTUhzVFhhRk0z
            ZVBCMHdFWkN2V3pmMS9xV0ptZDVoYVEKPc2iZnjyNIi1InCELoqKLdzYNrtXXcOi
            LciSkfp8BDbNK1b2oH4Lys/tA0W/EjjJo4dNRWvhHLM5+cy4yZEVYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQnJpM3RvRk52c0Vsc2lm
            TW9rRi9jNUcrUUJSY0REbVMrUHRrV0tFYWdBClJWTXhtUUJLSkpTKzJQejNSWCtm
            TU5qVkRnZXJYbHF0V2ZhaW1sdUU3cXMKLS0tIDJvUHBoRFBDSXNTQmtrYy9UVVdU
            ck8wajY3RWFIMThDZzlpRHY0MFJkaXMKPUjJd8nLrG3CAR8C9e0nShlxY0AAioEd
            Tsor4kO2kTb7ON4wEMo/LjKo/b7p7uMVkig9OpyBFhV8EDxppeCCvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:24:01Z"
    mac: ENC[AES256_GCM,data:Aqdrtj5i4UaHJ+FsFvEkXwlohBu3I9xBK9Z8L4dSyo5DlDvKoT5kGiIJg8a3R8HESvqw96fHQrTuXo16C5g9NO763WXMM1tSxGvxt5ie6JLYGXc8b6djI1BSAvIuOWGRoRFgp7b9x9hVTl41Y6rlSyw9NGwhco5cnV7RFaP9EmA=,iv:8fdG4edsE6NXGOHT4TmOch8JeIaSKDOSOOPAuV13qYU=,tag:lPrKX8E9RSyLMLX6bc6KAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
