apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-prometheus-token
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:E+OtJiUFqMbczTOrQCpNT9M1jIZ86Eby5Zl2INYt4xVKrDLqMyD7+ttoA1BRVVOgFlmzHq7RkLVAWJCWGEYfLfbaXgCsM2r9xieYKppwidWZdUtJ8GatVJxSKsfcjGcTogIdZzlsCAwtxQVYWWTvP+9f4spPsD3ABabpMryzGxTBFrLz2QA0rBgW29iPbiU157m/H4BhYo+GMf6pnslXXTqMqYwPa9WWoS3JLMrfYx0rHOMPXTxm,iv:yzepvwTZV9ivkmUFI4sw9FM/oaKRTFuwaK/qBobIiMA=,tag:O2qZPqECO/qIJhhioJHQyQ==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVW9Iei9DcURMd0NrNWtl
            d0pBbC94Tmo3S0p4a2NFQy93WmlpcU9OQ1cwClFLYjFlZEJmWlNkckhSMDB2YjhS
            SUZhUm9hK01leDQwTG1BYXlMNlVEdE0KLS0tIGprbnVQL20rSmMxb3ExY2I1M1Zh
            Mmp1NGVuWUp3TG9JV3FOZG5jQVBzOXcK1O0VviThMblTiKLF4lE87y2n0py2mKB+
            evi8Mj67aKZItAx034dxjw/oq0RiKciYpFt32csOtLguuE+CAqJGcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVDBPUlF6NmQzckNLUlhh
            Y0gzS1owMTFjazNXSllDMWpYM3Y0SUl3ZlVvClF2LzZiU1IvekZKQ0RONkVYQ0NW
            ZnZKSnR0RkFzbnk4Q3l0YVNISG1LMlUKLS0tIHBwRVlWQzNJSmpSYUhNZ2UxcUF2
            NlBxbi9HT25kcS9EaityMFNCdWdtc0UKd70xC1IWsIofgTC/f6t9W26xqeCfi6cr
            mVUXJSlmtURsnLdWz0VDj7A43kHCwOpr180pV3TQFt8GueYPNzI4bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVnduUjZrWStVTVN5TFhU
            Mml2NnpRTHlpa1hJMy9Tc0pEVzhzQXcxYlhBClVjMXBvRWp1bS82bVlPVk5uaVdi
            SHdrWm1SdE1UOWMxNWpPckpNbFNmeVEKLS0tIDB6SGJ5VXZwY1BLNE1FNDl2MVV2
            WE9LS2dHejhsSitLdHVpaHNSeStpa2cKIPghtYYwD6mqeoGl1tRvmulocS8Dv00n
            tkYgnSymOKwwtXGp5MdYVt8dJwIZStyMCQG2H3WH8cp9C5+xUl7iTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bC9aQi9MZ093b2hRb09v
            S1o2RHd2elRWQmlYamw2bThOSC9nc0w1RUVnCkQxeG9EdThBV3l5VHF1RXNXVCtl
            V1dIeDdBZm1jM3AxNkZQWHJVNDlQTlkKLS0tIFFKbDFPbG9DVjVPd20yS21mZ1lI
            TGdObFpGS1N3dnV4eHJZblZsSXpEVmcKmHP4wsL9bt/oKZ4NG+XlM7YlY8+80fUM
            DT15WB9xjccI+6O/JYFtj/IizwsQp+QDe0ewbLdVAuQ/C/gc8lLKYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T23:42:00Z"
    mac: ENC[AES256_GCM,data:7EBGNnb5wDCBJywLrG3pc2oEtxI8IQtPNHJqwaHWQVEAEe/4l02NFQZSIJuO7sQP+tfiA8a+6bUwnTa87BjEpQAoqAFC2wLXJjnllWnh12suL/uX7nuYpBdMC9KFPtrCC/NEnc60z6oDXHJfV6U8/+maWifPbDu9F66HE+g+4Zk=,iv:YIyq3js8T86YTSdlSc8NS1iH/28vLDLhDB+gZ0rVN5U=,tag:5C6PxYnh7qhmY3rZvkENew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
