---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui-tls
  namespace: open-webui
spec:
  secretName: open-webui-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ai.dimensiondoor.xyz
