#ENC[AES256_GCM,data:haBsKxt07P2cZzhIdKRYPn0HvtCx+ZS0ksuZ7N3W7UJo7IOd4GrRTpuz1JSA99rPlI82RvFMLh++HyuroRQeQ5eOl6Z94bAV,iv:gxy3cJzkLAX5YomX/F53Xg34sEn9e2bIKhMItadLjy0=,tag:ZGALgYmkPek7zCziASZ2kw==,type:comment]
#ENC[AES256_GCM,data:+QLLxotrAwgl5PINE94rrX8YM3DgbABcLHviumSb0SkPGoxT+lURAJlmMqDOfqvg793vD/wuQcGwmhKTbXu7,iv:4kOAZXf7S5ZLieF8MIGpQdIt1w63XX+/kawiXS/HRAw=,tag:JFThCb/bRLR9ukBzBpxkWA==,type:comment]
#ENC[AES256_GCM,data:UkFLBA1n7RijnIHOjqJb9mAvGpxqR0vfxXNqleA0lwbXYdaMJw==,iv:EVHG3GXpb0LgBAr+l4n65ZjzOfHBALm0d+/X0Y0yH2I=,tag:8BtCAilyFFNLBBH5Zn6LAg==,type:comment]
#ENC[AES256_GCM,data:EJNwTVBTf67xv3Nz5OPay5faiHFCo4FYJ1Isg/+s3qJOz4xBavR2RUjIX521/jj3W7arlG7kcWPoW8ernhhNsSTphpnR0luJfK+R9Y69W3zL6X27erPTHcpietZuDe+ym575ZWtWyO7+GUfLFqnlCW+dWQ==,iv:n/pyTy1A1+1ipKDtFd9m9cDAQACslA8HVSTID9izge0=,tag:h287vKofi1NETn//SWV2AA==,type:comment]
apiVersion: ENC[AES256_GCM,data:6Yo=,iv:BSZx3OErnCSQ9ZkkOwRWQr3kM1n/nyPkJPiYdTQc0KY=,tag:B/JZRS30Fyx5f+htMXu4LA==,type:str]
kind: ENC[AES256_GCM,data:phcVORuB,iv:+51h5nojCXnUlOZifbCWburHaWl39pFURMKCU7eAJy0=,tag:p/8XcGPW/XblQBZbdkLzeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KDpRUBeacd6TeVTA2n2oNajK,iv:KPW+DttC5SjsgqzihDXlbOaR+CnN4REDkbVXfJbWMPU=,tag:Xf3D/O9SjWfONabmcbCb0A==,type:str]
    namespace: ENC[AES256_GCM,data:tXfXP/5IqMk0pg==,iv:jc+G8gxlu5ii9kqka6bJ3h7Ll7WWzHpMp1Lx6QGoF70=,tag:29OGvNV2GVUBkjAqZdGLNg==,type:str]
stringData:
    #ENC[AES256_GCM,data:5eEvN8QHlsA68zFAO41TyrvmitkI4vYi1mCNTH+/3yGTKE0y,iv:/tx77u+D24SI2L93JeGajqFJ5k84+eVd6KVDxP1XAWM=,tag:JVk/zmF+6+zF3xVWOPawzw==,type:comment]
    secret-key: ENC[AES256_GCM,data:KhZLjpQtXOO7m9GivTWADndvcAOTFZrJjaTxwRzTNJDoLYV1SPlOekp+8c0F2prBr1A8Ldjb5sMJzKIkcng8/w==,iv:vnV2kFP7ybeAsqi+bE/DyNpLpwAX4OI4zxe3HeIED90=,tag:ZYF+aByZOhp+rsOL/Ej8Lw==,type:str]
    openai-api-keys: ENC[AES256_GCM,data:QKFuygkEHC7c+D3rf4z6tbey0xsqnqFTGkL/IzLnRe0fOrur8WECEnTZ,iv:rCdV0xrABSqIGP5qd1HoOnnas308ArXiOiUMOPRHMEI=,tag:YslKAK2LvYsiGjkBcCCICA==,type:str]
    tavily-api-key: ENC[AES256_GCM,data:6XMfPPpVXmVxUcdQn2G7ZCH7peQs6+sq7+w0eRjS1d3JEJU7mXNGKak=,iv:elhilpn0eOqBMVr7VwBzKK4YGftJtO7dlRl2UP/rrpE=,tag:jfuXPLjmLweY2JdtVzDuwg==,type:str]
    oauth_client_secret: ENC[AES256_GCM,data:gTChhOH9bu1tAAjnF0FLTRuO3E+gLjyK+I22rlSrWJfoa/TeObm32TzBc4A=,iv:AMa7RbDDgC3Eiv2YLjS2g74cEiaxEyzHIseT0c6BvT0=,tag:potNhRMNlb5AbwW6VCpp1g==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmtGNUEwb3RJc0dLbFJF
            b09CWDdyejdCU0VpazJUWUtpSjk5RDVBeEdFCjlzL1JpRFVsZzJWYzNVbU43eWFC
            R1FnZnJmenU1RFpRVXlqMGpRZ1R6Tm8KLS0tIHhUNE9IQVl4ZzltcFhnMGtDd0or
            UDlDYUpHaDdoNG00WlZxUVo4NmxqYUUKR93OAo6Osi0GDBFZWfLuhQCzZuKq/UW1
            ZNssbj0EjjV/W/fWPLK9v7JQ/x5btMeKttjE4VPacXUEDCycEWdydw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVXhKWjd0QnBDd2JkbUhk
            MjRvMFBXOTdQcGd1cmJPdVB3eEQwbkJvOVNzCkhiNjRWNUQ2WTNnanJhN1pBRlRZ
            T1F1MEYzRjVvQ2ZhRm1Bb29EdlhnQ2MKLS0tIFIwQ2pBU3N5MEtvb28yVnNZVE9i
            STJyVDc5RVI0NHdXMGxvZ2pyNXlVWXMKxn4Hquy1Ctz8Lbs9nbhvle3s8dOZgzjR
            YcTOBHgjXGsNCMJ/LWcukCey/WQro+a9AOtvjozO3uoxL5unX0gZxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDBTZXBpTHpIeW1WUE15
            cEV0L2wxZ2lLYXJwMlZJdVdZYi92L0lmR0dzCmZsVDBZdDF6a3IzSkpMS2l0QkxQ
            V0o0em1pbkxpRk1iUmNmUlZYanVXR0EKLS0tIHVsUms3YnY0ejFGazAyb1ZSbisx
            MXJGVjJHaHZmTXcyVGRJMlZ4VU95RzQKJfMkUXk7HjepCsuh2RUxfS8w/7Zgbhqd
            IN90GBtju1rxEAQDgmz5wvtAVqlrPTXvhFNhlaamxWZ/c4SydxSEeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWEZGTXB6WlA1dXgwQXBl
            OGZrSEQ0a2RqTGthZUQ5YlN3MS9jeVhmOVd3CjZ1SHZnd2RKSU9sZ2lnOFh3WURE
            Vnpua0toWG16QUJuUW9CWnpFUzJTV3cKLS0tIDZYQWJ3RE9YQit6U2ZyTmpyMU4v
            ZUpBNFhOSWQ1TlJqSG5ZYmxIVyt2QTgKXd28ROSthToVvqnLWoAHAi/1NWHHU1ps
            pP3Pcw5eyIiiNAgpBK7BqY93PHdfKg1wlMOX4GaUcy2ozBlofldGMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T00:29:31Z"
    mac: ENC[AES256_GCM,data:ig82uQ5WzYvSsTDEM6tgEeL/BP9xygZMQp8y+h0Hv7z4AmKWzNsvfZRgc+lYAz0DDoDnOlN62B1ovWecJTa+iAu7ce1i/+TbLB/ji/HiirnBheYaThXeHKNuJ9Q7QYatgNXHGl9r2v/D3abxv/qrn+aplu2kH6WB5h+6FW8ZOLg=,iv:aapU5uF83g+Jc4Jc5YQnI359PiLDZlt494ZBOZFVUJM=,tag:FPf63zSRR9sjk1QPzKqQUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
